
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-eks-demo
  labels:
    app: spring-eks-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-eks-demo
  template:
    metadata:
      labels:
        app: spring-eks-demo
    spec:
      containers:
        - name: spring-eks-demo
          image: REPLACE_IMAGE
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
