server.port=8080

# Expose essential actuator endpoints for k8s + observability
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true

# Make health endpoint show readiness/liveness groups (useful for k8s)
management.endpoint.health.show-details=never
